[package]
name = "yatotp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac-sha1 = "0.1"
chrono = "0.4"
hmac = "0.12"
sha-1 = "0.10"
sha2 = "0.10"
data-encoding = "2.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tempfile = "3.2"
anyhow = "1.0"
